facebook:
  title: "Fed Up"
  caption: "http://fedup.dosomething.org"
  description: "What is your school serving you for lunch? Snap a pic and submit it to Do Something's Fed Up and you'll be eligible to win a scholarship."

home:
  order:
    - "vc DESC"
    - "posts.created_at DESC"

filters:
  ":state":
    constraints:
      ":state": "(?<state>[A-Z]{2})"
    where:
      "state": "state"
    order:
      - "vc DESC"
      - "posts.created_at DESC"
  "eatit":
    fields:
      - "COUNT(up.*) as upcount"
    joins:
      - "LEFT JOIN votes up on (up.voteable_id = posts.id and up.vote = 't')"
    order:
      - "upcount DESC"
  "tossit":
    fields:
      - "COUNT(down.*) as downcount"
    joins:
      - "LEFT JOIN votes down on (down.voteable_id = posts.id and down.vote = 'f')"
    order:
      - "downcount DESC"
  "eatit-:state":
    constraints:
      ":state": "(?<state>[A-Z]{2})"
    fields:
      - "COUNT(up.*) as upcount"
    joins:
      - "LEFT JOIN votes up on (up.voteable_id = posts.id and up.vote = 't')"
    where:
      "state": "state"
    order:
      - "upcount DESC"
  "tossit-:state":
    constraints:
      ":state": "(?<state>[A-Z]{2})"
    fields:
      - "COUNT(down.*) as downcount"
    joins:
      - "LEFT JOIN votes down on (down.voteable_id = posts.id and down.vote = 'f')"
    where:
      "state": "state"
    order:
      - "downcount DESC"


popups:
  # Put your popups here, e.g.:
  # 5: "test"

stats:
  - 'There are lots of ways to make change in your cafeteria.  Download <a href="http://www.dosomething.org/files/campaigns/fedup/FedUp_ActionGuide.pdf" target="_blank">the advocacy kit</a> to find out more.'
  - 'Check out the <a href="http://www.dosomething.org/files/campaigns/fedup/Lunch_Line.pdf" target="_blank">history of school lunch</a> to find out why your tray looks the way it does.'
  - "Most school lunch decisions are made on a local level - that means your school district decides what you eat."
  - "Ask your lunch lady if foods that are fried can be baked next time."
  - "Ask a cafeteria staff member how often food is delivered to school (if it's delivered more often, it's likely fresher!)"
  - "Is there variety in the produce your cafeteria serves? As long as you get 2-5 cups, your school can serve any fruit or veggie they want."
  - "Juices high in sugar make you tired - your school can provide water or milk instead to help keep your energy up."
  - "Grab some green stickers and stick 'em on the fresh foods in your cafeteria line."
  - "Buying local produce can actually be less expensive than what your school currently buys.  Many farmers markets will provide reduced rates for schools."
  - "Almost 50% of American students are eligible for free or reduced lunch."
  - "64% of schools prepare only a quarter of their entrees from scratch - that means prepackaged stuff is the majority of what students eat."
