facebook:
  # title: Facebook post title
  # caption: Caption
  # description: Description
  
filters:
  # Put your filters here.  e.g.
  # ":state":
  #   constraints:
  #     ":state": "(?<state>[A-Z]{2})"
  #   where:
  #     "state": "state"
