connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: create_and_share

development:
  <<: *connection

test:
  <<: *connection

production:
  <<: *connection
