connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: create_and_share

development:
  <<: *connection

test:
  <<: *connection

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: create_and_share

