connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: create_and_share
  username: postgres

development:
  <<: *connection

test: &test
  <<: *connection
  database: create_and_share_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: create_and_share

cucumber:
  <<: *test
