connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: create_and_share_campaigns
  username: postgres
  password: zanzibar

development:
  <<: *connection

test: &test
  <<: *connection
  database: create_and_share_campaigns_test

staging: &staging
  <<: *connection
  database: create_and_share_campaigns

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: create_and_share_campaigns
